version: '3'
services:
  jupyter:
    build:
      context: ./jupyter-docker
      dockerfile: Dockerfile
    ports: 
      - "8888:8888"
    depends_on: 
      - postgres
    container_name: jupyter
    volumes:
      - ..:/home/jovyan/work:cached
  postgres:
    build:
      context: ./postgres-docker
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: password
      POSTRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    container_name: postgres
  pgadmin:
    build:
      context: ./pgadmin-docker
      dockerfile: Dockerfile
    environment:
      PGADMIN_DEFAULT_EMAIL: jovyan@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    container_name: pgadmin
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin: